/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_MainActivity */

#ifndef _Included_com_example_ndk_MainActivity
#define _Included_com_example_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_MainActivity
 * Method:    referenceAssignAndNew
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_MainActivity_referenceAssignAndNew
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    localReference
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_MainActivity_localReference
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    globalReference
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_MainActivity_globalReference
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    weekReference
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_MainActivity_weekReference
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
