/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_MainActivity */

#ifndef _Included_com_example_ndk_MainActivity
#define _Included_com_example_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_MainActivity
 * Method:    passBooleanReturnBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_ndk_MainActivity_passBooleanReturnBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    passByteReturnByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_example_ndk_MainActivity_passByteReturnByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    passCharReturnChar
 * Signature: (C)B
 */
JNIEXPORT jchar JNICALL Java_com_example_ndk_MainActivity_passCharReturnChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_example_ndk_MainActivity
 * Method:    passShortReturnShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_example_ndk_MainActivity_passShortReturnShort
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
