/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_methods_MainActivity */

#ifndef _Included_com_example_ndk_methods_MainActivity
#define _Included_com_example_ndk_methods_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_methods_MainActivity
 * Method:    NativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndk_methods_MainActivity_NativeAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_ndk_methods_MainActivity
 * Method:    NativeMulticate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndk_methods_MainActivity_NativeMulticate
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
